[package]
name = "mqtt-filelog"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
env_logger = "0.9"
paho-mqtt = "0.9"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
